site_name: DialogueQuest Manual
nav:
- Home: user/index.md
- Documentation:
  - user/index.md
  - dialogue_quest_tester.md
  - user/writing_dialogue.md
  - user/characters.md
  - user/statements/say.md
  - user/statements/flag.md
  - user/statements/choice.md
  - user/statements/branch.md
  - user/statements/signal.md
  - user/statements/call.md
  - user/statements/exit.md
  - user/statements/dq_bbcodes.md
  - developer/index.md
  - developer/setup.md
  - developer/exporting.md
  - developer/basics/examples.md
  - developer/basics/writing_dialogue.md
  - developer/basics/creating_characters.md
  - developer/basics/creating_dialogue.md
  - developer/basics/playing_dialogue.md
  - developer/basics/settings.md
  - developer/extending/extending_dialogue_quest.md
  - developer/extending/theming.md
  - developer/extending/custom_statements.md
  - developer/extending/custom_logic.md
  - developer/systems/flags.md
  - developer/systems/signals.md
docs_dir: .
theme: readthedocs
